// <auto-generated />
namespace AThousandCounts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class IPAddressString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IPAddressString));
        
        string IMigrationMetadata.Id
        {
            get { return "201403252135367_IPAddressString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
